--- #YAML:1.0
name:               WWW-Moviepilot
version:            0.02
abstract:           Interface to the moviepilot.de database
author:
    - Frank Wiegand <frank.wiegand@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON::Any:       0
    LWP::UserAgent:  0
    Test::More:      0
    URI:             0
    URI::Escape:     0
resources:
    repository:  git://github.com/haoess/perl-www-moviepilot.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
